<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/admin">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Site</li>
    <li class="breadcrumb-item active">Mensagens</li>
</ol>

<div class="row">
    <div class="col-12">
        <h1>Mensagens</h1>
        <p>Envie e gerencie as mensagens nesta seção!</p>
        <hr>
    </div>
    <?php if ($this->getParams(0) == 'adicionar'): ?>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Adicionar mensagem</div>
                <div class="card-body">
                    <form method="post" id="addMessage">

                        <div class="form-group">
                            <label><b>Título</b></label>
                            <input class="form-control" name="title">
                        </div>

                        <div class="form-group">
                            <label><b>Subtítulo</b></label>
                            <input class="form-control" name="subtitle">
                        </div>

                        <div class="form-group">
                            <label><b>Mensagem</b></label>
                            <textarea class="summernote" name="topic" id="topic"></textarea>
                        </div>

                        <br>
                        <button class="btn btn-block btn-primary" style="margin-top: 10px;">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    <?php else: ?>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Gerenciador</div>
                <div class="card-body" style="overflow-x: auto">
                    <table class="table table-striped table-bordered dt-responsive nowrap datatable" style="width:100%">
                        <thead>
                        <tr>
                            <th>Data das atualizações</th>
                            <th>Gerenciar</th>
                        </tr>
                        </thead>

                        <tbody>
                        <?= $this->communicateds->listall() ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    <?php endif ?>

</div>