<?php


function isLogged()

{
    return (isset($_SESSION['BangBang'])) ? true : isset($_COOKIE['BangBang']);
}

function getUsername()
{
    if (isset($_SESSION['BangBang'])) {
        return ucwords($_SESSION['BangBang']);
    }
    return ucwords($_COOKIE['BangBang']);
}

?>

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><?= APP_NAME ?> - Dashboard</title>
    <link href="<?= APP_ROOT ?>/resources/admin/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= APP_ROOT ?>/resources/admin/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>/resources/admin/assets/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="<?= APP_ROOT ?>/resources/admin/assets/css/sb-admin.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
    <link href="<?= APP_ROOT ?>/resources/admin/assets/css/core.css" rel="stylesheet">
    <link rel="shortcut icon" href="<?= APP_ROOT ?>/resources/admin/assets/images/icon.png"/>
    <script>window.scripts = [];</script>
</head>

<body class="fixed-nav sticky-footer" style="background-color: #1b1e21" id="page-top">
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="/admin"><b style="color:#fff;"><?= APP_NAME ?></b> <b>ADMIN</b></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="/admin">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">Dashboard</span>
                </a>
            </li>
            <?php if($this->permissions->node('messages')): ?>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Mensagens">
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#menu-li-4" data-parent="#exampleAccordion">
                        <i class="fa fa-fw fa-paper-plane"></i>
                        <span class="nav-link-text">Mensagens</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="menu-li-4">
                        <?php if($this->permissions->parent('messages', 'add')): ?>
                            <li>
                                <a href="/admin/site/mensagens/adicionar"><i class="fa fa-plus"></i> Adicionar mensagem</a>
                            </li>
                        <?php endif ?>
                        <?php if($this->permissions->parent('messages', 'edit')): ?>
                            <li>
                                <a href="/admin/site/mensagens/editar"><i class="fa fa-pencil"></i> Editar mensagem</a>
                            </li>
                        <?php endif ?>
                        <?php if($this->permissions->parent('messages', 'delete')): ?>
                            <li>
                                <a href="/admin/site/mensagens/deletar"><i class="fa fa-remove"></i> Deletar mensagem</a>
                            </li>
                        <?php endif ?>
                    </ul>
                </li>
            <?php endif ?>
        </ul>
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-double-left"></i>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="navbar-text mr-2 ml-2">
                Sessão iniciada: <?= getUsername() ?> (<?= \config\RemoteAddress::get() ?>)
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#logoutModal">
                    <i class="fa fa-fw fa-sign-out"></i>Sair
                </a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper">
    <div class="container-fluid">
        <?= $this->render(); ?>
    </div>
    <footer class="sticky-footer">
        <div class="container">
            <div class="text-center">
                <small><?= APP_NAME ?></small>
            </div>
        </div>
    </footer>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="logoutModalLabel">Tem certeza?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Após confirmar a saída, você será redirecionado a página de login e perderá acesso ao painel.
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-primary" href="/admin/home/login/logout">Confirmar</a>
                </div>
            </div>
        </div>
    </div>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/vendor/jquery/jquery.min.js"></script>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/vendor/chart.js/Chart.min.js"></script>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/vendor/datatables/jquery.dataTables.js"></script>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/vendor/datatables/dataTables.bootstrap4.js"></script>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/js/sb-admin.js"></script>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/js/sb-admin-datatables.js"></script>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/js/sb-admin-charts.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    <script src="<?= APP_ROOT ?>/resources/admin/assets/javascript/functions.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
    <script>
        $(function () {
            if (scripts instanceof Array) {
                $.each(scripts, function (index, fn) {
                    if (typeof fn === 'function') fn();
                });
            }
        });
    </script>
</div>
</body>

</html>
