<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title><?= APP_NAME ?> - Dashboard</title>

    <link href="<?= APP_ROOT ?>/resources/admin/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= APP_ROOT ?>/resources/admin/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>/resources/admin/assets/css/sb-admin.css" rel="stylesheet">
    <link rel="shortcut icon" href="<?= APP_ROOT ?>/resources/admin/assets/images/icon.png"/>
</head>
<body class="bg-dark">

<?= $this->render(); ?>

<script src="<?= APP_ROOT ?>/resources/admin/assets/vendor/jquery/jquery.min.js"></script>
<script src="<?= APP_ROOT ?>/resources/admin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?= APP_ROOT ?>/resources/admin/assets/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="<?= APP_ROOT ?>/resources/admin/assets/javascript/functions.js"></script>
</body>

</html>