<div class="container">
    <div class="card card-login mx-auto" style="margin-top: 20vh;">
        <div class="card-body" style="border-radius: 5px; border: solid 3px rgba(0,0,0,.2);">
            <div class="alert alert-success" style="display: none;"></div>
            <div class="alert alert-danger" style="display: none;"></div>
            <form method="post" id="authenticate">
                <input name="<?= $this->tokenId ?>" value="<?= $this->tokenValue?>" type="hidden">
                <input name="<?= $this->inputs['ip'] ?>" value="<?= \config\RemoteAddress::get() ?>" type="hidden">
                <div class="form-group">
                    <label for="username">Usuário</label>
                    <input class="form-control" id="username" name="<?= $this->inputs['username'] ?>"
                           placeholder="Insira seu usuário" required>
                </div>
                <div class="form-group">
                    <label for="password">Senha</label>
                    <input class="form-control" id="password" type="password" name="<?= $this->inputs['password'] ?>"
                           placeholder="Insira sua senha" required>
                </div>
                <div class="form-group">
                    <div class="form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" name="<?= $this->inputs['mode'] ?>" type="checkbox"> Continuar conectado
                        </label>
                    </div>
                </div>
                <div class="progress" style="display: none; height: 4px">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                         aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%; background-color: #34ce57"></div>
                </div>
                <br>
                <button class="btn btn-success btn-block"><i class="fa fa-lock"></i> Autenticar</button>
            </form>
        </div>
    </div>
</div>