<div style="margin-top: 10rem">
<center>
    <h3 class="cd-headline letters rotate-2">
        <span>Você é o meu </span>
        <span class="cd-words-wrapper">
				<b class="is-visible" style="font-weight: bold">amor</b>
				<b style="font-weight: bold">mundo</b>
                <b style="font-weight: bold">tudo.</b>
            </span>
    </h3>
</center>
</div>

<div style="margin-top: 10rem">
    <center>
        <a class="btn btn-outline-warning" href="/mensagens" style="font-size: 24px">Ir para <span style="font-weight: bold">mensagens</span></a>
    </center>
</div>

